import type { Metadata } from "next";
import { Anton, Bellota, Roboto_Flex, Overlock, Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const robotoLight = Roboto({
  weight: "300",
  subsets: ["latin"],
});

export const robotoBlack = Roboto({
  weight: "900",
  subsets: ["latin"],
});


export const robotoflex = Roboto_Flex({
  weight: "200",
  subsets: ["latin"],
});

export const anton = Anton({
  weight: "400",
  subsets: ["latin"],
});

export const bellota = Bellota({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});


export const overlock = Overlock({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mx-auto w-full max-w-[2440px]">
          {children}
        </div>
      </body>
    </html>
  );
}
